[package]
name = "rust-interpreter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
indexmap = "2.0.1"
thiserror = "1.0.43"

[dev-dependencies]
insta = "1.34.0"
